### ISSUE TITLE
bad alloc with when computing decompositions of (1,1,1,3,3) pentagon

### ISSUE THREAD

**Issue by saraedum** [flatsurf/sage-flatsurf#56]
This is probably only happening with  the changes in #51. And is most likely in a bug in libflatsurf.

Iterating through the decompositions of the unfolding of the (1,1,1,3,3) pentagon, I found the following exception:
```
Traceback (most recent call last):
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/dev/shm/ruth/survey/flatsurvey/worker/__main__.py", line 143, in <module>
    if __name__ == "__main__": worker()
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/dev/shm/ruth/survey/flatsurvey/worker/__main__.py", line 110, in process
    objects.provide(Worker).start()
  File "/dev/shm/ruth/survey/flatsurvey/worker/__main__.py", line 141, in start
    goal.resolve()
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 102, in resolve
    if producer.produce() != Producer.EXHAUSTED:
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 121, in produce
    if source.produce() != Producer.EXHAUSTED:
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 121, in produce
    if source.produce() != Producer.EXHAUSTED:
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 46, in produce
    self._notify_consumers(end - start)
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 52, in _notify_consumers
    if consumer.consume(self._current, cost) == Consumer.COMPLETED:
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 83, in consume
    self._resolved = self._consume(product, cost)
  File "/dev/shm/ruth/survey/flatsurvey/goals/saddle_connection.py", line 39, in _consume
    self._notify_consumers(cost)
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 52, in _notify_consumers
    if consumer.consume(self._current, cost) == Consumer.COMPLETED:
  File "/dev/shm/ruth/survey/flatsurvey/goals/flow_decomposition.py", line 47, in consume
    self._notify_consumers(cost + end - start)
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 52, in _notify_consumers
    if consumer.consume(self._current, cost) == Consumer.COMPLETED:
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 83, in consume
    self._resolved = self._consume(product, cost)
  File "/dev/shm/ruth/survey/flatsurvey/goals/orbit_closure.py", line 53, in _consume
    orbit_closure.update_tangent_space_from_flow_decomposition(decomposition)
  File "/dev/shm/ruth/sage-flatsurf/flatsurf/geometry/gl2r_orbit_closure.py", line 938, in update_tangent_space_from_flow_decomposition
    self.update_tangent_space_from_vector(v)
  File "/dev/shm/ruth/sage-flatsurf/flatsurf/geometry/gl2r_orbit_closure.py", line 948, in update_tangent_space_from_vector
    for gen, p in self.V2.decomposition(v):
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/pyflatsurf/vector.py", line 431, in decomposition
    return [(self.base_ring()(module.gen(i)), tuple(V(coefficients))) for (i, coefficients) in enumerate(zip(*vector)) if any(coefficients)]
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/pyflatsurf/vector.py", line 431, in <listcomp>
    return [(self.base_ring()(module.gen(i)), tuple(V(coefficients))) for (i, coefficients) in enumerate(zip(*vector)) if any(coefficients)]
cppyy.gbl.std.bad_alloc: exactreal::Element<exactreal::NumberField> exactreal::Module<exactreal::NumberField>::gen(long i) =>
    bad_alloc: std::bad_alloc
```

**Comment by saraedum** [comment]
Duplicate of https://github.com/flatsurf/intervalxt/issues/73 and https://github.com/flatsurf/flatsurf/issues/121. There's a RAM limit set with ulimit and we're hitting it after 15 hours.
