### ISSUE TITLE
EquiangularPolygons fails for (1,1,1,1,8) pentagon

### ISSUE THREAD

**Issue by saraedum** [flatsurf/sage-flatsurf#58]
This is probably only a problem with the changes in #51.

```
Traceback (most recent call last):
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/dev/shm/ruth/survey/flatsurvey/worker/__main__.py", line 143, in <module>
    if __name__ == "__main__": worker()
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/tmp/ruth/miniconda/envs/survey/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/dev/shm/ruth/survey/flatsurvey/worker/__main__.py", line 110, in process
    objects.provide(Worker).start()
  File "/dev/shm/ruth/survey/flatsurvey/worker/__main__.py", line 141, in start
    goal.resolve()
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 102, in resolve
    if producer.produce() != Producer.EXHAUSTED:
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 121, in produce
    if source.produce() != Producer.EXHAUSTED:
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 121, in produce
    if source.produce() != Producer.EXHAUSTED:
  File "/dev/shm/ruth/survey/flatsurvey/pipeline.py", line 42, in produce
    if self._produce() == Producer.EXHAUSTED:
  File "/dev/shm/ruth/survey/flatsurvey/goals/saddle_connection.py", line 16, in _produce
    self._connections = iter(self._surface.orbit_closure()._surface.saddle_connections(pyflatsurf.flatsurf.Bound(10, 0)))
  File "sage/misc/cachefunc.pyx", line 2310, in sage.misc.cachefunc.CachedMethodCallerNoArgs.__call__ (build/cythonized/sage/misc/cachefunc.c:12684)
  File "/dev/shm/ruth/survey/flatsurvey/objects/surface.py", line 62, in orbit_closure
    return GL2ROrbitClosure(self.translation_cover())
  File "sage/misc/cachefunc.pyx", line 2310, in sage.misc.cachefunc.CachedMethodCallerNoArgs.__call__ (build/cythonized/sage/misc/cachefunc.c:12684)
  File "/dev/shm/ruth/survey/flatsurvey/objects/ngons.py", line 136, in translation_cover
    S = similarity_surfaces.billiard(self.polygon())
  File "sage/misc/cachefunc.pyx", line 2310, in sage.misc.cachefunc.CachedMethodCallerNoArgs.__call__ (build/cythonized/sage/misc/cachefunc.c:12684)
  File "/dev/shm/ruth/survey/flatsurvey/objects/ngons.py", line 109, in polygon
    E = EquiangularPolygons(*self.angles)
  File "/dev/shm/ruth/sage-flatsurf/flatsurf/geometry/polygon.py", line 1998, in __init__
    raise ValueError("each angle must be > 0 and < 2 pi")
ValueError: each angle must be > 0 and < 2 pi
```

**Comment by saraedum** [comment]
Ok. I guess the error message is just fine and simply should not feed invalid input.

**Comment by videlec** [comment]
On the other hand we might want to support `2pi` angles... However, this is doable by building "manually" a triangulated version.
