### ISSUE TITLE
tests fail on master on Travis CI

### ISSUE THREAD

**Issue by videlec** [flatsurf/sage-flatsurf#63]
The two builds with SAGE_OPTIONALS="sage,flipper,eantic,exactreal" fail their tests because apparently of exactreal
```
sage -t --long flatsurf/geometry/polygon.py

**********************************************************************

File "flatsurf/geometry/polygon.py", line 1871, in flatsurf.geometry.polygon.EquiangularPolygons

Failed example:

    P(K(1)) # optional: eantic

Expected:

    Polygon: (0, 0), (1, 0), ((1/2*c0 ~ 0.70710678), (-1/2*c0+1 ~ 0.29289322))

Got:

    Polygon: (0, 0), (1, 0), (1/2*c0, -1/2*c0 + 1)

**********************************************************************

File "flatsurf/geometry/polygon.py", line 1892, in flatsurf.geometry.polygon.EquiangularPolygons

Failed example:

    P(R(1)) # optional: exactreal

Exception raised:

    Traceback (most recent call last):

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run

        self.compile_and_execute(example, compiler, test.globs)

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sage/doctest/forker.py", line 1123, in compile_and_execute

        exec(compiled, globs)

      File "<doctest flatsurf.geometry.polygon.EquiangularPolygons[14]>", line 1, in <module>

        P(R(Integer(1))) # optional: exactreal

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/flatsurf/geometry/polygon.py", line 2229, in __call__

        s, t = matrix(base_ring, [slopes[-1], slopes[n - 2]]).solve_left(vertices[0] - vertices[n - 2])

      File "sage/matrix/matrix2.pyx", line 387, in sage.matrix.matrix2.Matrix.solve_left (build/cythonized/sage/matrix/matrix2.c:6109)

        return self.transpose().solve_right(B, check=check)

      File "sage/matrix/matrix2.pyx", line 794, in sage.matrix.matrix2.Matrix.solve_right (build/cythonized/sage/matrix/matrix2.c:7160)

        P = P.fraction_field()

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/pyexactreal/exact_reals.py", line 677, in fraction_field

        raise NotImplementedError("ExactReals.fraction_field() is not implemented yet because gcd() is incomplete and __floordiv__ rounds to integers instead of performing exact division as expected by SageMath's FractionField_generic.")

    NotImplementedError: ExactReals.fraction_field() is not implemented yet because gcd() is incomplete and __floordiv__ rounds to integers instead of performing exact division as expected by SageMath's FractionField_generic.

**********************************************************************

File "flatsurf/geometry/polygon.py", line 1894, in flatsurf.geometry.polygon.EquiangularPolygons

Failed example:

    P(R(R.random_element([0.2, 0.3]))) # random output, optional: exactreal

Exception raised:

    Traceback (most recent call last):

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sage/doctest/forker.py", line 681, in _run

        self.compile_and_execute(example, compiler, test.globs)

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/sage/doctest/forker.py", line 1123, in compile_and_execute

        exec(compiled, globs)

      File "<doctest flatsurf.geometry.polygon.EquiangularPolygons[15]>", line 1, in <module>

        P(R(R.random_element([RealNumber('0.2'), RealNumber('0.3')]))) # random output, optional: exactreal

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/flatsurf/geometry/polygon.py", line 2229, in __call__

        s, t = matrix(base_ring, [slopes[-1], slopes[n - 2]]).solve_left(vertices[0] - vertices[n - 2])

      File "sage/matrix/matrix2.pyx", line 387, in sage.matrix.matrix2.Matrix.solve_left (build/cythonized/sage/matrix/matrix2.c:6109)

        return self.transpose().solve_right(B, check=check)

      File "sage/matrix/matrix2.pyx", line 794, in sage.matrix.matrix2.Matrix.solve_right (build/cythonized/sage/matrix/matrix2.c:7160)

        P = P.fraction_field()

      File "/home/travis/miniconda/envs/test-environment/lib/python3.7/site-packages/pyexactreal/exact_reals.py", line 677, in fraction_field

        raise NotImplementedError("ExactReals.fraction_field() is not implemented yet because gcd() is incomplete and __floordiv__ rounds to integers instead of performing exact division as expected by SageMath's FractionField_generic.")

    NotImplementedError: ExactReals.fraction_field() is not implemented yet because gcd() is incomplete and __floordiv__ rounds to integers instead of performing exact division as expected by SageMath's FractionField_generic.

**********************************************************************

File "flatsurf/geometry/polygon.py", line 1896, in flatsurf.geometry.polygon.EquiangularPolygons

Failed example:

    _.base_ring() # optional: exactreal

Expected:

    Real Numbers as (Number Field in c0 with defining polynomial x^2 - 2 with c0 = 1.414213562373095?)-Module

Got:

    Algebraic Real Field

**********************************************************************

1 item had failures:

   4 of  38 in flatsurf.geometry.polygon.EquiangularPolygons

    [485 tests, 4 failures, 13.35 s]
```

**Comment by videlec** [comment]
@saraedum Could you have a look?

**Comment by saraedum** [comment]
Fixed in the GL2ROrbitClosure branch ;)
https://github.com/flatsurf/sage-flatsurf/pull/51/files#diff-340c380047f42d9e5638de4c1fadc4e5R1908
